name: pianqian
main: com.dislikeyou.pianqian.Main
version: 0.0.3
commands:
  pianqian:
    description: nothing
    usage: /<command>
  pqreload:
    description: nothing
    usage: /<command>
  pqsell:
    description: nothing
    usage: /<command>
depend: [Vault]